# You don't usually need to edit this file.
# If it does not fit your personal use case, docker-compose.override.yml is a preferred way to go.

version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    image: postgres:12
    container_name: slothpixel-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slothpixel
  mongo:
    image: mongo:4
    container_name: slothpixel-mongo
  redis:
    image: redis:5
    container_name: slothpixel-redis
  core:
      build:
        context: .
        dockerfile: Dockerfile
      image: slothpixel/core
      # Override this command with your script if existing does not fit your needs
      entrypoint: bash docker/main-launch.sh
      ports:
        - "5000:5000"
        - "5100:5100"
      environment:
        POSTGRES_URL: postgresql://postgres:postgres@slothpixel-postgres/slothpixel
        POSTGRES_TEST_URL: postgresql://postgres:postgres@slothpixel-postgres/slothpixel_test
        READONLY_POSTGRES_URL: postgresql://readonly:readonly@slothpixel-postgres/slothpixel
        REDIS_URL: redis://slothpixel-redis:6379/0
        REDIS_TEST_URL: redis://slothpixel-redis:6379/1
        MONGODB_URL: mongodb://slothpixel-mongo/slothpixel
        INIT_POSTGRES_HOST: slothpixel-postgres
      volumes:
        - .:/usr/src
      links:
        - postgres
        - mongo
        - redis
      container_name: slothpixel-core
